routes/web.php
<?php

// Front-office -> Routes

// Index
Route::get('/', 'PageController@index')->name('index');

// Sobre
Route::get('/acerca', 'PageController@acerca')->name('about');

// Contactos
Route::get('/contacto', 'ContactController@index')->name('contacts');
Route::get('/contacto/sendemail', 'ContactController@sendMail')->name('sendmail');

// Blog
Route::get('/blog', 'BlogController@index')->name('blog');
Route::get('/blog/{post}', 'BlogDetailController@index')->name('blogDetail');
Route::post('/blog', 'CommentController@store')->name('storeComment');

// Landing Page
Route::get('/landingpage', 'LandingPageController@index')->name('landingPage');

// Back-Office -> Routes

Auth::routes();

Route::get('/accountconfirmation/{user}', 'ConfirmationController@index')->name('confirmation.index');
Route::post('/accountconfirmation/{user}', 'ConfirmationController@update')->name('confirmation.update');

Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','RevalidateBackHistory']], function () {

    // Home
    Route::get('/', 'HomeController@index')->name('home');

    // Ajuda
    Route::get('/ajuda', 'HomeController@ajuda')->name('help');

    // Publicações - Blog
    Route::resource('/posts', 'PostController');

    // Comentários - Blog
    Route::resource('/comments', 'CommentController');
/*  Route::get('/comments', 'CommentController@index')->name('comments');
    Route::get('/comments/{$comment_id}', 'CommentController@show')->name('showcomments'); */

    // landing Page - Blog
    Route::resource('/landingpages', 'LandingPageController');

    // Testimonial - Blog
    Route::resource('/testimonials', 'TestimonialController');

    // Users
    Route::resource('/users', 'UserController');

    // Logout
    Route::get('/logout', 'Auth/LoginController@logout');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roleToStr(){
        switch ($this->role) {
            case 'Employer':
                return 'Funcionário';
            case 'Admin':
                return 'Administrador';
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Mail;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\StoreUserRequest;
use App\Mail\SendAccountConfirmation;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Database\Eloquent\SoftDeletes;


class UserController extends Controller{

    public function index(){
      if (Auth::user()->role == "Admin") {
        $users = User::orderBy('name', 'asc')
        ->get();
        return view('backoffice.users.list', compact('users'));
      }else {
        abort(403);
      }
    }

    public function create(){
      if (Auth::user()->role == "Admin") {
        $user = new User;
        return view('backoffice.users.add', compact('user'));
      }else {
        abort(403);
      }
    }

    public function store(StoreUserRequest $request){
      $fields = $request->validated();
      $user = new User();
      $user->fill($fields);
      $user->password = Hash::make('?_estudarP0rtugalMX!P4ssword');
      $user->save();
      $userid = $user->id;
      $username = $user->name;
      Mail::to($user->email)->send(new SendAccountConfirmation($userid, $username));
      return redirect()->route('users.index')->with('success', 'Utilizador criado com sucesso!');
    }

    public function show(User $user){
      if (Auth::user()->role == "Admin") {
        return view('backoffice.users.show', compact('user'));
      }else {
        abort(403);
      }
    }

    public function edit(User $user){
      if (Auth::user()->role == "Admin") {
        return view('backoffice.users.edit', compact('user'));
      }else {
        abort(403);
      }
    }

    public function update(UpdateUserRequest $request, User $user){
      $fields=$request->validated();
      $user->fill($fields);
      $user->save();
      return redirect()->route('users.index')->with('success', 'Utilizador editado com sucesso!');
    }

    public function destroy(User $user){
      $user->delete();
      return redirect()->route('users.index')->with('success', 'Utilizador eliminado com sucesso!');;
    }
}

resources/views/backoffice/users/add.blade.php
@extends('backoffice.master-back')

@section('title', 'Utilizadores')

@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Criação Utilizador</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{route('home')}}" class="text-dark">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('users.index')}}" class="text-dark">Utilizadores</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Adicionar Utilizador</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 text-right ">
            <a href="javascript:history.go(-1)" class="btn btn-md btn-primary shadow-sm">
                <i class="fas fa-chevron-left text-white-50 mr-2"></i>
                Voltar à Listagem
            </a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3>Adicionar Utilizador</h3><br>
                    <form action="{{route('users.store')}}" method="post" class="form-group" enctype="multipart/form-data">
                        @csrf
                        @include('backoffice.users.partials.add-edit')
                        <div class="text-right">
                            <div class="form-group col-md-12 text-right mt-3 ml-3">
                                <button type="submit" class="btn btn-md btn-primary text-white mr-1" name="confirm" title='Editar Utilizador'>
                                    Adicionar
                                </button>
                                <a href="{{route('users.index')}}" class="btn btn-md btn-secondary text-white mr-1 my-1" name="btn_cancelar" id="btn_cancelar" title='Cancelar Edição'>Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/backoffice/users/edit.blade.php
@extends('backoffice.master-back')

@section('title', 'Utilizadores')

@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Editar Utilizador</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{route('home')}}" class="text-dark">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('users.index')}}" class="text-dark">Utilizadores</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Editar Utilizador</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 text-right ">
            <a href="javascript:history.go(-1)" class="btn btn-md btn-primary shadow-sm">
                <i class="fas fa-chevron-left text-white-50 mr-2"></i>
                Voltar à Listagem
            </a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="" action="{{route('users.update', $user)}}" method="post">
                        @csrf
                        @method('PUT')
                        @include('backoffice.users.partials.add-edit')
                        <div class="text-right">
                            <div class="form-group col-md-12 text-right mt-3 ml-3">
                                <button type="submit" class="btn btn-md btn-success text-white mr-1" name="confirm" title='Guardar Alteração'> <i class="far fa-save mr-2"></i>
                                    Guardar
                                </button>
                                <a href="{{route('users.index')}}" class="btn btn-md btn-secondary text-white mr-1 my-1" name="btn_cancelar" id="btn_cancelar" title='Cancelar Edição'>Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/backoffice/users/list.blade.php
@extends('backoffice.master-back')

@section('title', 'Utilizadores')

@section('styleLinks')
<link rel="stylesheet" href="{{asset('/css/style-users.css')}}">
@endsection

@section('content')
@include('backoffice.users.partials.modal')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Listagem de Utilizadores</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{route('home')}}" class="text-dark">Dashboard</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Utilizadores</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 text-right ">
            <a href="{{route('users.create')}}" class="btn btn-md btn-primary shadow-sm">
                <i class="fas fa-plus text-white-50 mr-2"></i> Adicionar Utilizador
            </a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if (count($users))
                    <div class="table-responsive">
                        <table id="dataTable" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Endereço Eletrónico</th>
                                    <th>Função</th>
                                    <th style="width:120px; text-align: center;">Opções</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>
                                        @if ($user->role == "Admin")Administrador
                                        @else Funcionário
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a class="btn btn-sm btn-outline-primary rounded" href="{{route('users.show', $user)}}" title='Visualizar'>
                                            <i class="fas fa-eye"></i>
                                        </a>

                                        <a class="btn btn-sm btn-outline-warning rounded" href="{{route('users.edit', $user)}}" title='Editar'>
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>

                                        @if (Auth::user()->id == $user->id)
                                        <a class="btn btn-sm btn-outline-danger rounded disabled" href="">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                        @else
                                        <form method="POST" action="{{route('users.destroy',$user)}}" role="form" class="d-inline-block form_post_id" title='Eliminar'>
                                            @csrf
                                            @method("DELETE")
                                            <button type="button" class="btn btn-sm btn-outline-danger rounded" data-toggle="modal" data-target="#eliminarPublicacao" data-title="{{$user->name}}" data-id="{{$user->id}}">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @else
                    <h5 style="text-align: center">Não existem utilizadores registados.</h5>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@section("scripts")
<script>
    $(document).ready(function() {
        $('#dataTable').DataTable({
            "columnDefs": [{
                    "orderable": false,
                    "targets": 3
                },

                {
                    "width": "120px",
                    "targets": 0
                },

                {
                    "width": "130px",
                    "targets": 2
                },
                {
                    "width": "120px",
                    "targets": 3
                }

            ],
            "order": [
                [2, "asc"]
            ],

            "language": {
                'url': '//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese.json'
            }
        });

    });
    $(document).ready(function() {
        $('#eliminarPublicacao').on('show.bs.modal', function(e) {
            $("#eliminar").click(function() {
                $(e.relatedTarget).parent().submit();
            });
            $("#titulo").text($(e.relatedTarget).data("title"));
        });
    });

    $('#eliminarPublicacao').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget);
        var recipient = button.data('whatever');
        var modal = $(this);
        modal.find('.modal-body input').val(recipient);
    });
</script>
@endsection

@endsection

resources/views/backoffice/users/show.blade.php
@extends('backoffice.master-back')

@section('title', 'Utilizadores')

@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Visualização do Utilizador</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{route('home')}}" class="text-dark">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('users.index')}}" class="text-dark">Utilizadores</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Visualização Detalhada</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 text-right ">
            <a href="javascript:history.go(-1)" class="btn btn-md btn-primary shadow-sm">
                <i class="fas fa-chevron-left text-white-50 mr-2"></i>
                Voltar à Listagem
            </a>
            <a href="{{route('users.edit', $user)}}" class="btn btn-md btn-warning shadow-sm" style="color:white;">
                <i class="fas fa-pencil-alt text-white-50 mr-2"></i> Editar Utilizador
            </a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3><b>{{$user->name}}</b></h3><br>
                    <h5 style="line-height: 1.6"><b>Email: </b>{{$user->email}}</h5>
                    <h5 style="line-height: 1.6"><b>Função: </b>@if($user->role == "Admin")Administrador @else Funcionário @endif</h5>
                    <h5 style="line-height: 1.6"><b>Data de criação: </b>{{date('d/m/Y', strtotime($user->created_at))}}</h5>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection