routes/web.php
<?php

// Front-office -> Routes

// Index
Route::get('/', 'PageController@index')->name('index');

// Sobre
Route::get('/acerca', 'PageController@acerca')->name('about');

// Contactos
Route::get('/contacto', 'ContactController@index')->name('contacts');
Route::get('/contacto/sendemail', 'ContactController@sendMail')->name('sendmail');

// Blog
Route::get('/blog', 'BlogController@index')->name('blog');
Route::get('/blog/{post}', 'BlogDetailController@index')->name('blogDetail');
Route::post('/blog', 'CommentController@store')->name('storeComment');

// Landing Page
Route::get('/landingpage', 'LandingPageController@index')->name('landingPage');

// Back-Office -> Routes

Auth::routes();

Route::get('/accountconfirmation/{user}', 'ConfirmationController@index')->name('confirmation.index');
Route::post('/accountconfirmation/{user}', 'ConfirmationController@update')->name('confirmation.update');

Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','RevalidateBackHistory']], function () {

    // Home
    Route::get('/', 'HomeController@index')->name('home');

    // Ajuda
    Route::get('/ajuda', 'HomeController@ajuda')->name('help');

    // Publicações - Blog
    Route::resource('/posts', 'PostController');

    // Comentários - Blog
    Route::resource('/comments', 'CommentController');
/*  Route::get('/comments', 'CommentController@index')->name('comments');
    Route::get('/comments/{$comment_id}', 'CommentController@show')->name('showcomments'); */

    // landing Page - Blog
    Route::resource('/landingpages', 'LandingPageController');

    // Testimonial - Blog
    Route::resource('/testimonials', 'TestimonialController');

    // Users
    Route::resource('/users', 'UserController');

    // Logout
    Route::get('/logout', 'Auth/LoginController@logout');
});

app/Landingpage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Landingpage extends Model
{
    protected $fillable = ['title', 'description', 'tags', 'backgroundimage1', 'backgroundimage2','contact1', 'contact2'];
    protected $table = 'landingpages';
}

app/Http/Controllers/LandingPageController.php
<?php

namespace App\Http\Controllers;

use App\Landingpage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\UpdateLadingpageRequest;
use Illuminate\Support\Facades\Storage;
use Auth;

class LandingpageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $landingpage = DB::table('landingpages')->first();


        $testimonials = DB::table('testimonials')->get();
        


        $ip_address=$_SERVER['REMOTE_ADDR'];

        $query = @unserialize(file_get_contents('http://ip-api.com/php/'.$ip));
         if($query && $query['status'] == 'success')
        {
          DB::table('views')->insert( ['origin'=>"Landingpage",'local'=>$query['country'],'created_at' => date("Y-m-d",time())] );
        }


        return view('frontoffice.landing-page.landingPage', compact('landingpage','testimonials'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Landingpage $landingpage
     * @return \Illuminate\Http\Response
     */
    public function show(Landingpage $landingpage)
    {
/*         $landingpage = DB::table('landingpages')->first();
        return view('frontoffice.landing-page.landingPage', compact('landingpage')); */
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Landingpage $landingpage
     * @return \Illuminate\Http\Response
     */
    public function edit(Landingpage $landingpage)
    {
        return view('backoffice.landingpages.edit', compact('landingpage'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Landingpage $landingpage
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLadingpageRequest $request, Landingpage $landingpage)
    {
        $fields = $request->validated();

        $landingpage->fill($fields);

        if ($request->hasFile('backgroundimage1')) {
            $backgroundimage1 = $request->file('backgroundimage1');
            $postImg1 = $landingpage->id . '_' . time() . '.' . $backgroundimage1->getClientOriginalExtension();

            if (!empty($landingpage->backgroundimage1)) {
                Storage::disk('public')->delete('landingpages-images/' . $landingpage->backgroundimage1);
            }

            Storage::disk('public')->putFileAs('landingpages-images/', $backgroundimage1, $postImg1);
            $landingpage->backgroundimage1 = $postImg1;
        }

        if ($request->hasFile('backgroundimage2')) {
            $backgroundimage2 = $request->file('backgroundimage2');
            $postImg2 = $landingpage->id . '_' . time() . '.' . $backgroundimage2->getClientOriginalExtension();

            if (!empty($landingpage->backgroundimage2)) {
                Storage::disk('public')->delete('landingpages-images/' . $landingpage->backgroundimage2);
            }

            Storage::disk('public')->putFileAs('landingpages-images/', $backgroundimage2, $postImg2);
            $landingpage->backgroundimage2 = $postImg2;
        }

        // Data em que o registo é modificado
        $t = time();
        $landingpage->updated_at == date("Y-m-d", $t);
        $landingpage->save();

        return redirect()->route('landingpages.edit', 1)->with('success', 'Landing Page Editada com Sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Landingpage $landingpage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Landingpage $landingpage)
    {
        //
    }
}

resources/views/backoffice/landingpages/edit.blade.php
@extends('backoffice.master-back')

@section('styleLinks')
    <link rel="stylesheet" type="text/css" href="{{asset('/css/style-backoffice-posts.css')}}">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.min.css">
@endsection

@section('title', 'Editar Landing Page')

@section('content')
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-7 align-self-center">
                <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Editar Landing Page</h4>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb m-0 p-0">
                            <li class="breadcrumb-item"><a href="{{route('home')}}" class="text-dark">Dashboard</a></li>
                            <li class="breadcrumb-item text-muted active" aria-current="page">Editar Landing Page</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="{{route('landingpages.update', 1)}}" class="form-group"
                              enctype="multipart/form-data">
                            @csrf
                            @method("PUT")
                            @include('backoffice.landingpages.partials.add-edit')
                            <div class="text-right">
                                <div class="form-group col-md-12 text-right mt-3 ml-3">
                                    <button type="submit" class="btn btn-md btn-success text-white mr-1" name="ok" title="Guardar Landing Page"><i class="far fa-save mr-2"></i> Guardar
                                    </button>
                                    <button class="btn btn-md btn-primary text-white mr-1 my-1" title="Visualizar Landing Page">
                                        <i class="far fa-eye mr-2"></i> <a  style="text-decoration: none; color: white" href="{{route('landingpages.index', 1)}}" target="_blank"> Visualizar </a>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <!-- Contagem de carateres -->
    <script src="{{asset('/js/script-characters.js')}}"></script>

    <!-- Script Imagens -->
    <script src="{{asset('/js/script-landing.js')}}"></script>

    <script>
        $(function () {
            $('input[type=text], textarea').keyup();
        });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.js"></script>

    <script>
        $(document).ready(function () {
            $('#inputTagsLanding').tokenfield({
                autocomplete: {
                    delay: 100
                },
                showAutocompleteOnFocus: true
            });
            $('#inputTagsLanding_div').on('submit', function (event) {
                event.preventDefault();
                if ($.trim($('#inputTagsLanding').val()).length == 0) {
                    alert("Please Enter Atleast one Skill");
                    return false;
                }
            });
        });
    </script>
@endsection