routes/web.php
<?php

// Front-office -> Routes

// Index
Route::get('/', 'PageController@index')->name('index');

// Sobre
Route::get('/acerca', 'PageController@acerca')->name('about');

// Contactos
Route::get('/contacto', 'ContactController@index')->name('contacts');
Route::get('/contacto/sendemail', 'ContactController@sendMail')->name('sendmail');

// Blog
Route::get('/blog', 'BlogController@index')->name('blog');
Route::get('/blog/{post}', 'BlogDetailController@index')->name('blogDetail');
Route::post('/blog', 'CommentController@store')->name('storeComment');

// Landing Page
Route::get('/landingpage', 'LandingPageController@index')->name('landingPage');

// Back-Office -> Routes

Auth::routes();

Route::get('/accountconfirmation/{user}', 'ConfirmationController@index')->name('confirmation.index');
Route::post('/accountconfirmation/{user}', 'ConfirmationController@update')->name('confirmation.update');

Route::group(['prefix' => 'backoffice', 'middleware' => ['auth','RevalidateBackHistory']], function () {

    // Home
    Route::get('/', 'HomeController@index')->name('home');

    // Ajuda
    Route::get('/ajuda', 'HomeController@ajuda')->name('help');

    // Publicações - Blog
    Route::resource('/posts', 'PostController');

    // Comentários - Blog
    Route::resource('/comments', 'CommentController');
/*  Route::get('/comments', 'CommentController@index')->name('comments');
    Route::get('/comments/{$comment_id}', 'CommentController@show')->name('showcomments'); */

    // landing Page - Blog
    Route::resource('/landingpages', 'LandingPageController');

    // Testimonial - Blog
    Route::resource('/testimonials', 'TestimonialController');

    // Users
    Route::resource('/users', 'UserController');

    // Logout
    Route::get('/logout', 'Auth/LoginController@logout');
});

resources/views/backoffice/partials/footer.blade.php
<footer class="footer text-muted">
    <p style="font-size: 14px; margin-bottom: 5px; margin-top: 5px; text-align: center">&copy;
        <script>
            document.write(new Date().getFullYear());
        </script>
        Copyright <a href="http://mexico.eportugal.test/" target="_blank">Estudar Portugal</a> Todos os direitos reservados.
    </p>
</footer>

resources/views/backoffice/partials/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" href="{{route('home')}}" aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>

                <li class="list-divider"></li>

                <li class="nav-small-cap">
                    <span class="hide-menu">Gerir Conteúdos</span>
                </li>

                <li class="sidebar-item {{Route::is('posts.*')?'selected':''}}">
                    <a class="sidebar-link sidebar-link" href="{{route('posts.index')}}" aria-expanded="false">
                        <i data-feather="file-text" class="feather-icon"></i>
                        <span class="hide-menu">Publicações</span>
                    </a>
                </li>

                <li class="sidebar-item {{Route::is('comments.*')?'selected':''}}">
                    <a class="sidebar-link sidebar-link" href="{{route('comments.index')}}" aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon"></i>
                        <span class="hide-menu">Comentários</span>
                    </a>
                </li>

                <li class="sidebar-item  {{Route::is('landingpages.*') ? 'selected' : ''}}">
                    <a class="sidebar-link sidebar-link" href="{{route('landingpages.edit', 1)}}" aria-expanded="false">
                        <i data-feather="file" class="feather-icon"></i>
                        <span class="hide-menu">Landing Page</span>
                    </a>
                </li>

                <li class="sidebar-item  {{Route::is('testimonials.*') ? 'selected' : ''}}">
                    <a class="sidebar-link sidebar-link" href="{{route('testimonials.index')}}" aria-expanded="false">
                        <i data-feather="user" class="feather-icon"></i>
                        <span class="hide-menu">Testemunhos</span>
                    </a>
                </li>

                <li class="list-divider"></li>

                @if (Auth::user()->role == "Admin")
                <li class="nav-small-cap">
                    <span class="hide-menu">Outras Ferramentas</span>
                </li>
                <li class="sidebar-item {{Route::is('users.*') ? 'selected' : ''}}">
                    <a class="sidebar-link sidebar-link" href="{{route('users.index')}}" aria-expanded="false">
                        <i data-feather="users" class="feather-icon"></i>
                        <span class="hide-menu">Utilizadores</span>
                    </a>
                </li>
                @endif
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

resources/views/backoffice/partials/topbar.blade.php
<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md">
        <div class="navbar-header" data-logobg="skin6">
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <div class="navbar-brand">
                <!-- Logo icon -->
                <a href="{{route('home')}}">
                    <b class="logo-icon">
                        <!-- Dark Logo icon -->
                        <img src="{{asset('/media/logo-icon.png')}}" alt="homepage" class="dark-logo" />
                        <!-- Light Logo icon -->
                        <img src="{{asset('/media/logo-icon.png')}}" alt="homepage" class="light-logo" />
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        <!-- dark Logo text -->
                        <img src="{{asset('/media/logo-text.png')}}" alt="homepage" class="dark-logo" />
                        <!-- Light Logo text -->
                        <img src="{{asset('/media/logo-light-text.png')}}" class="light-logo" alt="homepage" />
                    </span>
                </a>
            </div>
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav float-right mr-auto ml-5 pl-2">

            </ul>
            <ul class="navbar-nav float-right">
                <li class="nav-item dropdown float-right mr-auto ml-5 pl-3" style="color: #6d6d6d; font-size: 2px">
                    <a class="nav-link dropdown-toggle" href="http://mexico.eportugal.test/" target="_blank" title="Ver Website">
                        <i data-feather="monitor" class="svg-icon mb-1"></i>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="ml-2 d-none d-lg-inline-block"><span>Olá,</span> <span class="text-dark">{{Auth::user()->name}}</span> <i data-feather="chevron-down" class="svg-icon"></i></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                        <a class="dropdown-item" href="{{route('help')}}"><i data-feather="help-circle" class="svg-icon mr-2 ml-1"></i>
                            Ajuda</a>
                        <div class="dropdown-divider"></div>
                        <form action="{{route('logout')}}" method="post">
                            @csrf
                            <button class="dropdown-item" type="submit"><i data-feather="power" class="svg-icon mr-2 ml-1"></i>Logout</button>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>